---
- hosts: all
  vars_files:
    - host_vars/{{ ansible_hostname }}.yml
    - vars/dotfiles.yml
    - vars/gruvbox_palette.yml
    - vars/zsh_plugin_list.yml
  roles:
    #- dotfiles
    #- i3wm
    #- zsh
    - lib
